### ISSUE TITLE
decide what to return in cases of EOF and error

### ISSUE THREAD

**Issue by dmalan** [cs50/lib50-cpp#12]

**Comment by dmalan** [comment]
Decided to return an empty `std::string` in cases of EOF and error (and if user just inputs a line ending). Calling convention can then be to check `std::string::empty` as needed. And if caller really wants to distinguish, can check `eofbit` (cf. http://www.cplusplus.com/reference/string/string/getline/).

Considered accepting an `istream` as input to `get_*` so that functions don't presume to use `std::cin`, but that'd be inconsistent with other ports, which all assume standard input.

Could throw an exception in cases of error, but exception handling isn't likely to be introduced in first weeks of a C++ CS50 variant. So keeping it simple.

**Comment by AndrejPetelin** [comment]
> Decided to return an empty std::string in cases of EOF and error (and if user just inputs a line ending). Calling convention can then be to check std::string::empty as needed. And if caller really wants to distinguish, can check eofbit (cf. http://www.cplusplus.com/reference/string/string/getline/).

@dmalan is that not going to be a problem though? If `std::cin` is put into EOF state `eofbit` will remain set until `std::cin.clear()` gets called, thus leaving it up to the caller to clear the stream if needed.

So either the caller has to clear the state before using either `std::cin` or `cs50::get_*` functions again, in which case the user can check `std::cin.eof()` or `cs50::get_*` clear cin, in which case the caller cannot check for EOF.
