### ISSUE TITLE
C++11 compatibility

### ISSUE THREAD

**Issue by AndrejPetelin** [cs50/lib50-cpp#2]
Hello :) I've implemented a couple of the functions from the list in C++11, so I was wondering about a couple of things.

Mainly what is the target environment for the library?

Would C++11 be permissible at all or should the code support C++98/C++2003?

The CS50 IDE uses the GNU C++ standard library that comes with GCC v4.8.4. The standard library has some serious issues with regex, making it unusable. While regex does makes the code more elegant it would require an upgrade of the standard library. Is there any chance this will happen (for example, the versions of g++ and clang++ that come from the Ubuntu 16.04 repos come with regex support out of the box, so upgrading the OS  to 16.04LTS would solve this issue, for example) or should the functions just check for valid input in old-school fashion, using loops?

Hope my fork comes in handy :)

**Comment by dmalan** [comment]
We should try to be more backwards-compatible than C++11, I think, particularly if teachers are using older environments. While we officially use C11 in CS50, the C library only assumes C99. And we definitely shouldn't assume an environment as new as Ubuntu 16.04. Indeed, most teachers, if using C++ for CS50's psets, are likely on Windows too.

Odds are loops aren't necessary for error-checking though. Cf. https://github.com/cs50/lib50-c/blob/master/src/cs50.c.

**Comment by AndrejPetelin** [comment]
Right, well, AFAIK the updated versions by me and Irene should be fully in line with the C++98 standard. As far as testing, though, while older versions of g++/clang++ on Linux systems shouldn't be a problem I can probably go as far back as Visual Studio 2010. Is that old enough? I don't really see any problems with the headers and functions we used, but just to be sure :)
