### ISSUE TITLE
The place of polymorphism in this library

### ISSUE THREAD

**Issue by cmlsharp** [cs50/lib50-cpp#5]
To what extent (if at all) do y'all think polymorphism should be used in this library? Templates could be used to reduce the volume of code, but if templates won't be covered before students are encouraged to view the library, this doesn't make much sense.

**Comment by IvanJasenov** [comment]
@crossroads1112 I think here the main target group is the beginners in CS and OOP paradigm. 
Templates would just mess them up, since they are really cryptic for debugging.

**Comment by dmalan** [comment]
Best if we keep the libraries as readable as possible for a course's earliest weeks!
