### ISSUE TITLE
Question about eprintf

### ISSUE THREAD

**Issue by irenenaya** [cs50/lib50-cpp#7]
@dmalan : With respect to the eprintf function, are we looking for a user function that works similarly to the c++ output streams (i.e. cout, cerr)? Or should we go for a format similar to the c printf function?

In pre c++11 there are no variadic arguments other than the c style ones. C++11 does support variadic templates, which we could use in this case. The function would look like:

`eprint(a, b, c, d); // where a, b, c, d are variables of any type that has the << operator overloaded for the output stream`

The current c implementation works fine in c++ (of course) but the usage is very different. 
Because of how the output streams are implemented in c++, we could probably get away with a simple #define. Something like this would work:

`#define ecout std::cerr << __FILE__ << ":" << __LINE__ << ' '`

It is cheeky, i know :) 
But it's also really all it would take in c++. So do let us know which syntax would be better for the students to use and, if the c++ version is preferred and this line above is not ok, we'll try something else.

**Comment by dmalan** [comment]
Sorry for the very slow reply, @irenenaya! We're actually phasing out `eprintf` now, as you probably know!
