### ISSUE TITLE
A case for pointer as type

### ISSUE THREAD

**Issue by AndrejPetelin** [cs50/lib50-cpp#8]
I am aware that particularly with C programs it's more common to put the asterisk next to the variable as opposed to next to the type, however while both styles can be found in C++ code "in the wild", at least C++ literature generally seems to prefer the "pointer as a type" convension, in particular books by Bjarne Stroustrup and the C++ ISO committee FAQ, for example. Would it make more sense to adopt this style for the C++ library or is the `int *ptr` preferable to be consistent with the C library?

**Comment by IvanJasenov** [comment]
@AndrejPetelin I've noticed that too. But at the end of the day it's just a convention, a style CS50 standard has adopted. The same as big vs little endian for data transfer.

**Comment by AndrejPetelin** [comment]
@IvanJasenov huh?
